using Models;

namespace CategoryMap
{
    public static class StaticCategoryTree
	{
        private static Dictionary<string, Category> CategoryDict = new()
		{
			// Pieno produktai ir kiaušiniai
			{ "Pasterizuotas pienas", new() { NameLT = "Pasterizuotas pienas" } },
			{ "Pieno gėrimai", new() { NameLT = "Pieno gėrimai" } },
			{ "Ilgo galiojimo pienas", new() { NameLT = "Ilgo galiojimo pienas" } },
			{ "Sutirštintas pienas", new() { NameLT = "Sutirštintas pienas" } },
			{ "Sojų pienas", new() { NameLT = "Sojų pienas" } },
			{ "Augalinis pienas", new() { NameLT = "Augalinis pienas" } },
			{ "Sviestas", new() { NameLT =  "Sviestas" } },
			{ "Tepieji riebalų mišiniai", new() { NameLT = "Tepeji riebalų mišiniai" } },
			{ "Margarinas", new() { NameLT = "Margarinas" } },
			//{"Augaliniai sūrio pakaitalai", new() { NameLT = "Augaliniai sūrio pakaitalai" } },
			//{"Augaliniai majonezo pakaitalai", new(){ NameLT = "Augaliniai majonezo pakaitalai" } },
			//{"Augaliniai gėrimai", new() { NameLT = "Augaliniai gėrimai"} },
			//{"Augaliniai grietinėlės pakaitalai", new() { NameLT = "Augaliniai grietinėlės pakaitalai" } },
			//{"Augaliniai jogurto ir desertų pakaitalai", new() {NameLT = "Augaliniai jogurto ir desertų pakaitalai" } },
			//{"Augaliniai sviesto pakaitalai", new() { NameLT = "Augaliniai sviesto pakaitalai" } },
			{"Pienas ir gėrimai be laktozės", new() { NameLT = "Pienas ir gėrimai be laktozės" } },
			//{"Grietinė be laktozės", new() { NameLT = "Grietinė be laktozės" } },
			{"Jogurtai ir desertai be laktozės", new() { NameLT = "Jogurtai ir desertai be laktozės" } },
			//{"Sūriai be laktozės", new() { NameLT = "Sūriai be laktozės"} },
			//{"Sviestas ir margarinas be laktozės", new() { NameLT = "Sviestas ir margarinas be laktozės" } },
			//{"Varškė be laktozės", new() { NameLT = "Varškė be laktozės" } },
			{"Grietinė", new() { NameLT = "Grietinė" } },
			//{"Grietinėlė", new() { NameLT = "Grietinėlė" } },
			{"Fermentiniai sūriai", new() { NameLT = "Fermentiniai sūriai" } },
			{"Kietieji sūriai", new() { NameLT = "Kietieji sūriai" } },
			{"Pelėsiniai sūriai", new() { NameLT = "Pelėsiniai sūriai" } },
			{"Lydyti sūriai", new() { NameLT = "Lydyti sūriai" } },
			{"Varškės sūriai", new() { NameLT = "Varškės sūriai" } },
			//{"Ožkų ir avių pieno sūriai", new() { NameLT = "Ožkų ir avių pieno sūriai" } },
			{"Mocarelos ir buratos sūriai", new() { NameLT = "Mocarelos ir buratos sūriai" } },
			{"Maskarponės ir rikotos sūriai", new() { NameLT = "Maskarponės ir rikotos sūriai" } },
			{"Fetos ir brinzos sūriai", new() { NameLT = "Fetos ir brinzos sūriai" } },
			{"Tepamieji sūriai", new() { NameLT = "Tepamieji sūriai" } },
			//{"Sūriai, skirti kepti", new() { NameLT = "Sūriai, skirti kepti" } },
			{"Sūrio užkandžiai ir sūrio lazdelės", new() {NameLT = "Sūrio užkandžiai ir sūrio lazdelės" } },
			{"Majonezas", new() { NameLT = "Majonezas"} },
			{"Kefyras ir kefyro gėrimai", new() { NameLT = "Kefyras ir kefyro gėrimai" } },
			{"Rūgpienis", new() { NameLT = "Rūgpienis"} },
			{"Raugintos pasukos", new() { NameLT = "Raugintos pasukos" } },
			{"Jogurtai be pagardų", new() { NameLT = "Jogurtai be pagardų" } },
			{"Jogurtai su pagardais", new() { NameLT = "Jogurtai su pagardais" } },
			{"Geriamieji jogurtai", new() { NameLT = "Gėriamieji jogurtai" } },
			//{"Desertiniai batonėliai", new() { NameLT = "Desertiniai batonėliai" } },
			//{"Desertai", new() { NameLT = "Desertai" } },
			{"Varškė", new() { NameLT = "Varškė" } },
			{"Grūdėta varškė", new() { NameLT = "Grūdėta varškė" } },
			{"Tepamoji varškė", new() { NameLT = "Tepamoji varškė" } },
			{"Desertinė varškė", new() { NameLT = "Desertinė varškė" } },
			{"Varškės sūreliai", new() { NameLT = "Varškės sūreliai" } },
			{"Vištų kiaušinai", new() { NameLT = "Vištų kiaušiniai" } },
			{"Putpelių kiaušiniai", new() { NameLT = "Putpelių kiaušiniai"} },		
			//// Daržovės ir vaisiai
	        {"Pomidorai ir agurkai", new() { NameLT = "Pomidorai ir agurkai"} },
            {"Paprikos ir baklažanai", new() { NameLT = "Paprikos ir baklažanai"} },
            {"Bulvės, morkos ir kopūstai", new() { NameLT = "Bulvės, morkos ir kopūstai"} },
            {"Svogūnai, porai ir česnakai", new() { NameLT = "Svogūnai, porai ir česnakai"} },
            {"Būrokėliai ir kiti šakniavaisiai", new() { NameLT = "Būrokėliai ir kiti šakniavaisiai"} },
            {"Salotos ir jų mišiniai", new() { NameLT = "Salotos ir jų mišiniai"} },
            {"Prieskoninės daržovės ir žolelės", new() { NameLT = "Prieskoninės daržovės ir žolelės"} },
            {"Kukurūzai, žirniai, pupelės ir smidrai", new() { NameLT = "Kukurūzai, žirniai, pupelės ir smidrai"} },
            {"Moliūgai ir cukinijos", new() { NameLT = "Moliūgai ir cukinijos"} },
            {"Brokoliai", new() { NameLT = "Brokoliai"} },
   //         {"Marinuotos, raugintos ir sūdytos daržovės", new() { NameLT = "Marinuotos, raugintos ir sūdytos daržovės"} },
            {"Bananai", new() { NameLT = "Bananai"} },
            {"Citrusiniai vaisiai", new() { NameLT = "Citrusiniai vaisiai"} },
            {"Obuoliai ir kriaušės", new() { NameLT = "Obuoliai ir kriaušės"} },
            {"Vynuogės ir uogos", new() { NameLT = "Vynuogės ir uogos"} },
            {"Egzotiniai vaisiai", new() { NameLT = "Egzotiniai vaisiai"} },
            {"Melionai", new() { NameLT = "Melionai"} },
            {"Kaulavaisiai", new() { NameLT = "Kaulavaisiai"} },
            {"Avokadai", new() { NameLT = "Avokadai"} },
   //         {"Apdoroti vaisiai ir uogos", new() { NameLT = "Apdoroti vaisiai ir uogos"} },
           {"Grybai", new() { NameLT = "Grybai"} },
			////Bakalėja
   //         {"Švieži makaronai", new() { NameLT = "Švieži makaronai"} },
   //         {"Ilgieji ir plokštieji makaronai", new() { NameLT = "Ilgieji ir plokštieji makaronai"} },
   //         {"Trumpieji makaronai", new() { NameLT = "Trumpieji makaronai"} },
   //         {"Smulkieji makaronai", new() { NameLT = "Smulkieji makaronai"} },
   //         {"Vamzdeliniai ir lazanijos makaronai", new() { NameLT = "Vamzdeliniai ir lazanijos makaronai"} },
   //         {"Kiaušininiai makaronai", new() { NameLT = "Kiaušininiai makaronai"} },
   //         {"Pilno grūdo makaronai", new() { NameLT = "Pilno grūdo makaronai"} },
   //         {"Grikiai", new() { NameLT = "Grikiai"} },
   //         {"Kvietinės ir miežinės kruopos", new() { NameLT = "Kvietinės ir miežinės kruopos"} },
   //         {"Perlinės kruopos", new() { NameLT = "Perlinės kruopos"} },
   //         {"Manų kruopos", new() { NameLT = "Manų kruopos"} },
   //         {"Kitos krupos", new() { NameLT = "Kitos krupos"} },
   //         {"Dribsniai", new() { NameLT = "Dribsniai"} },
   //         {"Sausi pusryčiai", new() { NameLT = "Sausi pusryčiai"} },
   //         {"Dribsniai košėms", new() { NameLT = "Dribsniai košėms"} },
   //         {"Javainių batonėliai", new() { NameLT = "Javainių batonėliai"} },
   //         {"Bulvių traškučiai", new() { NameLT = "Bulvių traškučiai"} },
   //         {"Padažai traškučiams", new() { NameLT = "Padažai traškučiams"} },
   //         {"Kukurūzų traškučiai", new() { NameLT = "Kukurūzų traškučiai"} },
   //         {"Kepinta duona ir duonos traškučiai", new() { NameLT = "Kepinta duona ir duonos traškučiai"} },
   //         {"Kiti užkandžiai", new() { NameLT = "Kiti užkandžiai"} },
   //         {"Krekeriai ir sūrūs sausainiai", new() { NameLT = "Krekeriai ir sūrūs sausainiai"} },
   //         {"Kukurūzų lazdelės ir spragėsiai", new() { NameLT = "Kukurūzų lazdelės ir spragėsiai"} },
   //         {"Juodoji arbata", new() { NameLT = "Juodoji arbata"} },
   //         {"Žolelių arbata", new() { NameLT = "Žolelių arbata"} },
   //         {"Kita arbata", new() { NameLT = "Kita arbata"} },
   //         {"Šventinė arbata", new() { NameLT = "Šventinė arbata"} },
   //         {"Diabetinis maistas", new() { NameLT = "Diabetinis maistas"} },
   //         {"Sojų produktai", new() { NameLT = "Sojų produktai"} },
   //         {"Funkcinis maistas", new() { NameLT = "Funkcinis maistas"} },
   //         {"Kvietiniai miltai", new() { NameLT = "Kvietiniai miltai"} },
   //         {"Pilno grūdo miltai", new() { NameLT = "Pilno grūdo miltai"} },
   //         {"Kiti miltai", new() { NameLT = "Kiti miltai"} },
   //         {"Miltiniai mišiniai", new() { NameLT = "Miltiniai mišiniai"} },
   //         {"Sėlenos ir sėmenys", new() { NameLT = "Sėlenos ir sėmenys"} },
   //         {"Grynieji prieskoniai", new() { NameLT = "Grynieji prieskoniai"} },
   //         {"Pipirai", new() { NameLT = "Pipirai"} },
   //         {"Prieskonių mišiniai", new() { NameLT = "Prieskonių mišiniai"} },
   //         {"Universalūs prieskoniai", new() { NameLT = "Universalūs prieskoniai"} },
   //         {"Prieskonių ruošiniai patiekalams", new() { NameLT = "Prieskonių ruošiniai patiekalams"} },
   //         {"Prieskoniai mėsai", new() { NameLT = "Prieskoniai mėsai"} },
   //         {"Prieskoniai žuviai", new() { NameLT = "Prieskoniai žuviai"} },
   //         {"Marinatai", new() { NameLT = "Marinatai"} },
   //         {"Žolelių mišiniai", new() { NameLT = "Žolelių mišiniai"} },
   //         {"Greitai paruošiamos sriubos", new() { NameLT = "Greitai paruošiamos sriubos"} },
   //         {"Greitai paruošiami makaronai", new() { NameLT = "Greitai paruošiami makaronai"} },
   //         {"Greitai paruošiamos bulvių košės", new() { NameLT = "Greitai paruošiamos bulvių košės"} },
   //         {"Sultiniai", new() { NameLT = "Sultiniai"} },
   //         {"Huracán kava", new() { NameLT = "Huracán kava"} },
   //         {"Malta kava", new() { NameLT = "Malta kava"} },
   //         {"Kavos pupelės", new() { NameLT = "Kavos pupelės"} },
   //         {"Kavos kapsulės", new() { NameLT = "Kavos kapsulės"} },
   //         {"Tirpioji kava", new() { NameLT = "Tirpioji kava"} },
   //         {"Kavos kapsulės NESPRESSO® aparatams", new() { NameLT = "Kavos kapsulės NESPRESSO® aparatams"} },
   //         {"Kavos kapsulės Dolce Gusto® aparatams", new() { NameLT = "Kavos kapsulės Dolce Gusto® aparatams"} },
   //         {"Kakava", new() { NameLT = "Kakava"} },
   //         {"Kiti gėrimai", new() { NameLT = "Kiti gėrimai"} },
   //         {"Šventinė kava ir rinkiniai", new() { NameLT = "Šventinė kava ir rinkiniai"} },
   //         {"Konservuoti agurkai", new() { NameLT = "Konservuoti agurkai"} },
   //         {"Žaliosios alyvuogės", new() { NameLT = "Žaliosios alyvuogės"} },
   //         {"Juodosios alyvuogės", new() { NameLT = "Juodosios alyvuogės"} },
   //         {"Konservuoti pomidorai", new() { NameLT = "Konservuoti pomidorai"} },
   //         {"Konservuoti burokėliai", new() { NameLT = "Konservuoti burokėliai"} },
   //         {"Konservuoti kukurūzai", new() { NameLT = "Konservuoti kukurūzai"} },
   //         {"Konservuoti žirneliai", new() { NameLT = "Konservuoti žirneliai"} },
   //         {"Konservuotos pupelės", new() { NameLT = "Konservuotos pupelės"} },
   //         {"Konservuotos paprikos", new() { NameLT = "Konservuotos paprikos"} },
   //         {"Konservuoti daržovių mišiniai", new() { NameLT = "Konservuoti daržovių mišiniai"} },
   //         {"Kitos konservuotos ankštinės daržovės", new() { NameLT = "Kitos konservuotos ankštinės daržovės"} },
   //         {"Kitos konservuotos daržovės", new() { NameLT = "Kitos konservuotos daržovės"} },
   //         {"Konservuoti grybai", new() { NameLT = "Konservuoti grybai"} },
   //         {"Konservuoti vaisiai ir uogos", new() { NameLT = "Konservuoti vaisiai ir uogos"} },
   //         {"Uogienės ir džemai", new() { NameLT = "Uogienės ir džemai"} },
   //         {"Vaisių ir uogų tyrelės", new() { NameLT = "Vaisių ir uogų tyrelės"} },
   //         {"Medus", new() { NameLT = "Medus"} },
   //         {"Konservuotos sriubos", new() { NameLT = "Konservuotos sriubos"} },
   //         {"Ilgagrūdžiai ryžiai", new() { NameLT = "Ilgagrūdžiai ryžiai"} },
   //         {"Trumpagrūdžiai ir apvaliagrūdžiai ryžiai", new() { NameLT = "Trumpagrūdžiai ir apvaliagrūdžiai ryžiai"} },
   //         {"Rudieji ir laukiniai ryžiai", new() { NameLT = "Rudieji ir laukiniai ryžiai"} },
   //         {"Basmati ir kvapieji ryžiai", new() { NameLT = "Basmati ir kvapieji ryžiai"} },
   //         {"Plikyti ryžiai", new() { NameLT = "Plikyti ryžiai"} },
   //         {"Juodasis šokoladas", new() { NameLT = "Juodasis šokoladas"} },
   //         {"Baltasis šokoladas", new() { NameLT = "Baltasis šokoladas"} },
   //         {"Pieninis šokoladas", new() { NameLT = "Pieninis šokoladas"} },
   //         {"Šokoladiniai batonėliai", new() { NameLT = "Šokoladiniai batonėliai"} },
   //         {"Saldainiai ir šokoladas", new() { NameLT = "Saldainiai ir šokoladas"} },
   //         {"Sausainiai ir meduoliai", new() { NameLT = "Sausainiai ir meduoliai"} },
   //         {"Saldainių rinkiniai", new() { NameLT = "Saldainių rinkiniai"} },
   //         {"Kūčiukai", new() { NameLT = "Kūčiukai"} },
   //         {"Cukrus, saldikliai ir druska", new() { NameLT = "Cukrus, saldikliai ir druska"} },
   //         {"Kepinių papuošimai", new() { NameLT = "Kepinių papuošimai"} },
   //         {"Kepinių priedai", new() { NameLT = "Kepinių priedai"} },
   //         {"Sirupai", new() { NameLT = "Sirupai"} },
   //         {"Želė ir kiselius", new() { NameLT = "Želė ir kiselius"} },
   //         {"Kečupai", new() { NameLT = "Kečupai"} },
   //         {"Pomidorų padažai ir pasta", new() { NameLT = "Pomidorų padažai ir pasta"} },
   //         {"Majoneziniai padažai", new() { NameLT = "Majoneziniai padažai"} },
   //         {"Garstyčios", new() { NameLT = "Garstyčios"} },
   //         {"Krienai", new() { NameLT = "Krienai"} },
   //         {"Aitriųjų paprikų padažai", new() { NameLT = "Aitriųjų paprikų padažai"} },
   //         {"Kepsnių padažai", new() { NameLT = "Kepsnių padažai"} },
   //         {"Padažai salotoms", new() { NameLT = "Padažai salotoms"} },
   //         {"Padažai makaronams", new() { NameLT = "Padažai makaronams"} },
   //         {"Sojų padažai", new() { NameLT = "Sojų padažai"} },
   //         {"Desertiniai padažai", new() { NameLT = "Desertiniai padažai"} },
   //         {"Kiti padažai", new() { NameLT = "Kiti padažai"} },
   //         {"Užtepėlės", new() { NameLT = "Užtepėlės"} },
   //         {"Saulėgrąžų aliejus", new() { NameLT = "Saulėgrąžų aliejus"} },
   //         {"Alyvuogių aliejus", new() { NameLT = "Alyvuogių aliejus"} },
   //         {"Rapsų aliejus", new() { NameLT = "Rapsų aliejus"} },
   //         {"Kokosų aliejus", new() { NameLT = "Kokosų aliejus"} },
   //         {"Kitas aliejus", new() { NameLT = "Kitas aliejus"} },
   //         {"Actas ir koncentruotos citrinų sultys", new() { NameLT = "Actas ir koncentruotos citrinų sultys"} },
   //         {"Saldainiai", new() { NameLT = "Saldainiai"} },
   //         {"Sveriami saldainiai", new() { NameLT = "Sveriami saldainiai"} },
   //         {"Saldainių rinkiniai", new() { NameLT = "Saldainių rinkiniai"} },
   //         {"Batonėliai", new() { NameLT = "Batonėliai"} },
   //         {"Dražė", new() { NameLT = "Dražė"} },
   //         {"Guminukai", new() { NameLT = "Guminukai"} },
   //         {"Kramtomieji saldainiai", new() { NameLT = "Kramtomieji saldainiai"} },
   //         {"Pastilės, ledinukai ir kramtomoji guma", new() { NameLT = "Pastilės, ledinukai ir kramtomoji guma"} },
   //         {"Sausainiai", new() { NameLT = "Sausainiai"} },
   //         {"Vafliai", new() { NameLT = "Vafliai"} },
   //         {"Zefyrai", new() { NameLT = "Zefyrai"} },
   //         {"Šokolado ir riešutų kremai", new() { NameLT = "Šokolado ir riešutų kremai"} },
   //         {"Kiti saldumynai", new() { NameLT = "Kiti saldumynai"} },
   //         {"Žemės riešutai", new() { NameLT = "Žemės riešutai"} },
   //         {"Migdolų riešutai", new() { NameLT = "Migdolų riešutai"} },
   //         {"Lazdynų ir graikiniai riešutai", new() { NameLT = "Lazdynų ir graikiniai riešutai"} },
   //         {"Anakardžiai ir pistacijos", new() { NameLT = "Anakardžiai ir pistacijos"} },
   //         {"Kiti riešutai", new() { NameLT = "Kiti riešutai"} },
   //         {"Riešutų mišiniai", new() { NameLT = "Riešutų mišiniai"} },
   //         {"Riešutų ir džiovintų vaisių, uogų mišiniai", new() { NameLT = "Riešutų ir džiovintų vaisių, uogų mišiniai"} },
   //         {"Džiovinti vaisiai ir uogos", new() { NameLT = "Džiovinti vaisiai ir uogos"} },
   //         {"Sėklos", new() { NameLT = "Sėklos"} },
   //         {"Džiovintos daržovės ir grybai", new() { NameLT = "Džiovintos daržovės ir grybai"} },
   //         {"Šaltyje džiovinti vaisiai, uogos, daržovės", new() { NameLT = "Šaltyje džiovinti vaisiai, uogos, daržovės"} },
   //         {"Razinos ir spanguolės", new() { NameLT = "Razinos ir spanguolės"} },
   //         {"Abrikosai ir slyvos", new() { NameLT = "Abrikosai ir slyvos"} },
   //         {"Meksikos virtuvė", new() { NameLT = "Meksikos virtuvė"} },
   //         {"Tailando virtuvė", new() { NameLT = "Tailando virtuvė"} },
   //         {"Japonijos virtuvė", new() { NameLT = "Japonijos virtuvė"} },
   //         {"Kinijos virtuvė", new() { NameLT = "Kinijos virtuvė"} },
   //         //Kosmetika ir higiena
   //         {"Dantų šepetėliai", new() { NameLT = "Dantų šepetėliai"} },
   //         {"Dantų pastos", new() { NameLT = "Dantų pastos"} },
   //         {"Burnos skalavimo skysčiai", new() { NameLT = "Burnos skalavimo skysčiai"} },
   //         {"Dantų siūlai ir krapštukai", new() { NameLT = "Dantų siūlai ir krapštukai"} },
   //         {"Dantų protezų priežiūra", new() { NameLT = "Dantų protezų priežiūra"} },
   //         {"Makiažo valikliai ir veido prausikliai", new() { NameLT = "Makiažo valikliai ir veido prausikliai"} },
   //         {"Veido kremai", new() { NameLT = "Veido kremai"} },
   //         {"Naktiniai veido kremai", new() { NameLT = "Naktiniai veido kremai"} },
   //         {"Veido serumai ir paakių kremai", new() { NameLT = "Veido serumai ir paakių kremai"} },
   //         {"Veido kaukės", new() { NameLT = "Veido kaukės"} },
   //         {"Lūpų priežiūros priemonės", new() { NameLT = "Lūpų priežiūros priemonės"} },
   //         {"Kosmetinė vata ir krapštukai", new() { NameLT = "Kosmetinė vata ir krapštukai"} },
   //         {"Purškiamieji dezodorantai moterims", new() { NameLT = "Purškiamieji dezodorantai moterims"} },
   //         {"Purškiamieji dezodorantai vyrams", new() { NameLT = "Purškiamieji dezodorantai vyrams"} },
   //         {"Rutuliniai ir pieštukiniai dezodorantai moterims", new() { NameLT = "Rutuliniai ir pieštukiniai dezodorantai moterims"} },
   //         {"Rutuliniai ir pieštukiniai dezodorantai vyrams", new() { NameLT = "Rutuliniai ir pieštukiniai dezodorantai vyrams"} },
   //         {"Kvepalai moterims", new() { NameLT = "Kvepalai moterims"} },
   //         {"Kvepalai vyrams", new() { NameLT = "Kvepalai vyrams"} },
   //         {"Gabalinis tualetinis muilas", new() { NameLT = "Gabalinis tualetinis muilas"} },
   //         {"Skystas tualetinis muilas", new() { NameLT = "Skystas tualetinis muilas"} },
   //         {"Dušo želė", new() { NameLT = "Dušo želė"} },
   //         {"Vonios putos ir druska", new() { NameLT = "Vonios putos ir druska"} },
   //         {"Kūno odos priežiūros priemonės", new() { NameLT = "Kūno odos priežiūros priemonės"} },
   //         {"Saulės kosmetika", new() { NameLT = "Saulės kosmetika"} },
   //         {"Eteriniai aliejai", new() { NameLT = "Eteriniai aliejai"} },
   //         {"Kitos kūno priežiūros priemonės", new() { NameLT = "Kitos kūno priežiūros priemonės"} },
   //         {"Blakstienų tušai", new() { NameLT = "Blakstienų tušai"} },
   //         {"Makiažo pagrindai, pudros ir maskuokliai", new() { NameLT = "Makiažo pagrindai, pudros ir maskuokliai"} },
   //         {"Akių ir antakių pieštukai", new() { NameLT = "Akių ir antakių pieštukai"} },
   //         {"Lūpų dažai ir pieštukai", new() { NameLT = "Lūpų dažai ir pieštukai"} },
   //         {"Drėgnosios servetėlės", new() { NameLT = "Drėgnosios servetėlės"} },
   //         {"Pleistrai", new() { NameLT = "Pleistrai"} },
   //         {"Dezinfekcijos priemonės", new() { NameLT = "Dezinfekcijos priemonės"} },
   //         {"Prezervatyvai", new() { NameLT = "Prezervatyvai"} },
   //         {"Kitos medicininės prekės", new() { NameLT = "Kitos medicininės prekės"} },
   //         {"Vitaminų ir mineralų papildai", new() { NameLT = "Vitaminų ir mineralų papildai"} },
   //         {"Maisto papildai", new() { NameLT = "Maisto papildai"} },
   //         {"Namų vaistinėlė", new() { NameLT = "Namų vaistinėlė"} },
   //         {"Rankų odos priežiūros priemonės", new() { NameLT = "Rankų odos priežiūros priemonės"} },
   //         {"Pėdų odos priežiūros priemonės", new() { NameLT = "Pėdų odos priežiūros priemonės"} },
   //         {"Manikiūro ir pedikiūro reikmenys", new() { NameLT = "Manikiūro ir pedikiūro reikmenys"} },
   //         {"Skutimosi putos ir želė", new() { NameLT = "Skutimosi putos ir želė"} },
   //         {"Losjonai ir kremai po skutimosi", new() { NameLT = "Losjonai ir kremai po skutimosi"} },
   //         {"Skustuvai", new() { NameLT = "Skustuvai"} },
   //         {"Skutimosi peiliukai ir priedai", new() { NameLT = "Skutimosi peiliukai ir priedai"} },
   //         {"Depiliacinės priemonės", new() { NameLT = "Depiliacinės priemonės"} },
   //         {"Natūralus grožis", new() { NameLT = "Natūralus grožis"} },
   //         {"Plaukų šampūnai", new() { NameLT = "Plaukų šampūnai"} },
   //         {"Sausi plaukų šampūnai", new() { NameLT = "Sausi plaukų šampūnai"} },
   //         {"Plaukų balzamai", new() { NameLT = "Plaukų balzamai"} },
   //         {"Plaukų kaukės, serumai ir aliejus", new() { NameLT = "Plaukų kaukės, serumai ir aliejus"} },
   //         {"Šukuosenos formavimo priemonės", new() { NameLT = "Šukuosenos formavimo priemonės"} },
   //         {"Plaukų lakas", new() { NameLT = "Plaukų lakas"} },
   //         {"Plaukų dažai", new() { NameLT = "Plaukų dažai"} },
   //         {"Šukos ir šepečiai", new() { NameLT = "Šukos ir šepečiai"} },
   //         {"Higieniniai įklotai", new() { NameLT = "Higieniniai įklotai"} },
   //         {"Higieniniai paketai", new() { NameLT = "Higieniniai paketai"} },
   //         {"Tamponai", new() { NameLT = "Tamponai"} },
   //         {"Įklotai nelaikantiems šlapimo", new() { NameLT = "Įklotai nelaikantiems šlapimo"} },
   //         {"Intymios higienos servetelės", new() { NameLT = "Intymios higienos servetelės"} },
   //         {"Sauskelnės suaugusiems", new() { NameLT = "Sauskelnės suaugusiems"} },
   //         {"Kosmetikos rinkiniai", new() { NameLT = "Kosmetikos rinkiniai"} },
   //         //Namai ir laisvalaikis
   //         {"Virtuvės buitinė technika", new() { NameLT = "Virtuvės buitinė technika"} },
   //         {"Elektronikos prietaisai ir jų priedai", new() { NameLT = "Elektronikos prietaisai ir jų priedai"} },
   //         {"Asmeniniai elektronikos prietaisai ir jų priedai", new() { NameLT = "Asmeniniai elektronikos prietaisai ir jų priedai"} },
   //         {"Kompiuterijos prekės", new() { NameLT = "Kompiuterijos prekės"} },
   //         {"Kita elektronika", new() { NameLT = "Kita elektronika"} },
   //         {"Ilgintuvai ir jungtukai", new() { NameLT = "Ilgintuvai ir jungtukai"} },
   //         {"Elektros lemputės ir žibintuvėliai", new() { NameLT = "Elektros lemputės ir žibintuvėliai"} },
   //         {"Automobilų švaros priemonės", new() { NameLT = "Automobilų švaros priemonės"} },
   //         {"Automobiliniai oro gaivikliai", new() { NameLT = "Automobiliniai oro gaivikliai"} },
   //         {"Automobilių lemputės", new() { NameLT = "Automobilių lemputės"} },
   //         {"Tepalai, alyvos", new() { NameLT = "Tepalai, alyvos"} },
   //         {"Kitos automobilių prekės", new() { NameLT = "Kitos automobilių prekės"} },
   //         {"Kepsninės ir jų reikmenys", new() { NameLT = "Kepsninės ir jų reikmenys"} },
   //         {"Pridegimo priemonės", new() { NameLT = "Pridegimo priemonės"} },
   //         {"Vienkartiniai indai ir įrankiai", new() { NameLT = "Vienkartiniai indai ir įrankiai"} },
   //         {"Insekticidai, repelentai", new() { NameLT = "Insekticidai, repelentai"} },
   //         {"Lauko pramogų prekės", new() { NameLT = "Lauko pramogų prekės"} },
   //         {"Vandens pramogų prekės", new() { NameLT = "Vandens pramogų prekės"} },
   //         {"Sporto ir laisvalaikio prekės", new() { NameLT = "Sporto ir laisvalaikio prekės"} },
   //         {"Stovyklavimo prekės", new() { NameLT = "Stovyklavimo prekės"} },
   //         {"Pramogos lauke", new() { NameLT = "Pramogos lauke"} },
   //         {"Žūklės prekės", new() { NameLT = "Žūklės prekės"} },
   //         {"Indai", new() { NameLT = "Indai"} },
   //         {"Stalo įrankiai", new() { NameLT = "Stalo įrankiai"} },
   //         {"Taurės ir stiklinės", new() { NameLT = "Taurės ir stiklinės"} },
   //         {"Proginė atributika", new() { NameLT = "Proginė atributika"} },
   //         {"Žvakės ir žvakidės", new() { NameLT = "Žvakės ir žvakidės"} },
   //         {"Popierinės servetėlės", new() { NameLT = "Popierinės servetėlės"} },
   //         {"Vandens filtrai ir jų priedai", new() { NameLT = "Vandens filtrai ir jų priedai"} },
   //         {"Staltiesės", new() { NameLT = "Staltiesės"} },
   //         {"Virtuvinė tekstilė", new() { NameLT = "Virtuvinė tekstilė"} },
   //         {"Popierius, popieriaus gaminiai", new() { NameLT = "Popierius, popieriaus gaminiai"} },
   //         {"Piešimo, rašymo ir lipdymo priemonės", new() { NameLT = "Piešimo, rašymo ir lipdymo priemonės"} },
   //         {"Kitos kanceliarinės prekės", new() { NameLT = "Kitos kanceliarinės prekės"} },
   //         {"Žurnalai ir laikraščiai", new() { NameLT = "Žurnalai ir laikraščiai"} },
   //         {"Žurnalai vaikams", new() { NameLT = "Žurnalai vaikams"} },
   //         {"Kryžiažodžiai", new() { NameLT = "Kryžiažodžiai"} },
   //         {"Suagusiųjų populiarioji literatūra", new() { NameLT = "Suagusiųjų populiarioji literatūra"} },
   //         {"Spalvinimo knygos", new() { NameLT = "Spalvinimo knygos"} },
   //         {"Valstybinė atributika", new() { NameLT = "Valstybinė atributika"} },
			////Duonos gaminiai ir konditerija
			//{ "Šviežiai kepta tamsi duona", new() { NameLT = "Šviežiai kepta tamsi duona" } },
   //         { "Šviežiai kepta šviesi duona", new() { NameLT = "Šviežiai kepta šviesi duona" } },
   //         { "Šviežiai kepta šviesi duona su pagardais", new() { NameLT = "Šviežiai kepta šviesi duona su pagardais" } },
   //         { "Šviežiai keptas batonas", new() { NameLT = "Šviežiai keptas batonas" } },
   //         { "Šviežiai keptos nesaldžios bandelės", new() { NameLT = "Šviežiai keptos nesaldžios bandelės" } },
   //         { "Šviežiai keptos saldžios bandelės", new() { NameLT = "Šviežiai keptos saldžios bandelės" } },
   //         { "Šviežiai kepti užkandžiai", new() { NameLT = "Šviežiai kepti užkandžiai" } },
   //         { "Džiūvėsiai ir javinukai", new() { NameLT = "Džiūvėsiai ir javinukai" } },
   //         { "Riestainiai", new() { NameLT = "Riestainiai" } },
   //         { "Meduoliai", new() { NameLT = "Meduoliai" } },
   //         { "Tamsi duona", new() { NameLT = "Tamsi duona" } },
   //         { "Tamsi duona su pagardais", new() { NameLT = "Tamsi duona su pagardais" } },
   //         { "Šviesi duona", new() { NameLT = "Šviesi duona" } },
   //         { "Šviesi duona su pagardais", new() { NameLT = "Šviesi duona su pagardais" } },
   //         { "Batonas", new() { NameLT = "Batonas" } },
   //         { "Sumuštinių duona ir duonelės", new() { NameLT = "Sumuštinių duona ir duonelės" } },
   //         { "Duona be glitimo", new() { NameLT = "Duona be glitimo" } },
   //         { "Tortai", new() { NameLT = "Tortai" } },
   //         { "Plokštainiai ir vyniotiniai", new() { NameLT = "Plokštainiai ir vyniotiniai" } },
   //         { "Pyragaičiai ir desertai", new() { NameLT = "Pyragaičiai ir desertai" } },
   //         { "Šakočiai ir skruzdėlynai", new() { NameLT = "Šakočiai ir skruzdėlynai" } },
   //         { "Duonos pyragai", new() { NameLT = "Duonos pyragai" } },
   //         { "Keksai ir keksiukai", new() { NameLT = "Keksai ir keksiukai" } },
   //         { "Duonos lazdelės", new() { NameLT = "Duonos lazdelės" } },
   //         { "Duoniukai", new() { NameLT = "Duoniukai" } },
   //         { "Trapučiai ir kiti paplotėliai", new() { NameLT = "Trapučiai ir kiti paplotėliai" } },
   //         { "Kiti duonos gaminiai", new() { NameLT = "Kiti duonos gaminiai" } },
   //         { "Nesaldžios bandelės", new() { NameLT =  "Nesaldžios bandelės" } },
   //         { "Saldžios bandelės", new() { NameLT = "Saldžios bandelės" } },
   //         { "Spurgos", new() { NameLT = "Spurgos" } },
   //         //Šviežia mėsa
            { "Kiauliena", new() { NameLT = "Kiauliena" } },
            { "Jautiena", new() { NameLT = "Jautiena" } },
            { "Triušiena", new() { NameLT = "Triušiena" } },
            { "Aviena", new() { NameLT = "Aviena" } },
   //        { "Malta mėsa", new() { NameLT = "Malta mėsa" } },
   //         //Šviežia paukštiena
            { "Vištiena", new() { NameLT = "Vištiena" } },
            { "Kalakutiena", new() { NameLT = "Kalakutiena" } },
            { "Antiena", new() { NameLT = "Antiena" } },
   //        { "Malta paukštiena", new() { NameLT = "Malta paukštiena" } },
   //         //Šviežios mėsos ir paukštienos pusgaminiai
            { "Marinuota mėsa", new() { NameLT = "Marinuota mėsa" } },
   //         { "Marinuota paukštiena", new() { NameLT = "Marinuota paukštiena" } },
   //         { "Šviežios dešrelės", new() { NameLT = "Šviežios dešrelės" } },
   //         //Mėsos ir paukštienos gaminiai
            { "Dešrelės griliui", new() { NameLT = "Dešrelės griliui" } },
            { "Vytintos dešros", new() { NameLT = "Vytintos dešros" } },
   //         { "Šaltai rūkytos dešros", new() { NameLT = "Šaltai rūkytos dešros" } },
   //         { "Karštai rūkytos dešros", new() { NameLT = "Karštai rūkytos dešros" } },
            { "Virtos dešros", new() { NameLT = "Virtos dešros" } },
            { "Virtos dešrelės", new() { NameLT = "Virtos dešrelės" } },
   //         { "Parūkytos dešros ir dešrelės", new() { NameLT = "Parūkytos dešros ir dešrelės" } },
            { "Šaltai rūkyti gaminiai", new() { NameLT = "Šaltai rūkyti gaminiai" } },
            { "Karštai rūkyti gaminiai", new() { NameLT = "Karštai rūkyti gaminiai" } },
            { "Vytinti mėsos gaminiai", new() { NameLT = "Vytinti mėsos gaminiai" } },
            { "Virti, kepti ir sūdyti gaminiai", new() { NameLT = "Virti, kepti ir sūdyti gaminiai" } },
            { "Paštetai ir kiti gaminiai", new() { NameLT = "Paštetai ir kiti gaminiai" } },
            { "Mėsos ir paukštienos konservai", new() { NameLT = "Mėsos ir paukštienos konservai" } },
   //         { "Mėsos užkandžiai ir dešrelės", new() { NameLT = "Mėsos užkandžiai ir dešrelės" } },
   //         //Šviežios žuvys ir jūros gerybės
   //         { "Šviežia žuvis", new() { NameLT = "Šviežia žuvis" } },
   //         { "Jūrų gėrybės", new() { NameLT = "Jūrų gėrybės" } },
   //         { "Marinuota žuvis", new() { NameLT = "Marinuota žuvis" } },
   //         //Žuvų gaminiai
   //         { "Silkės ir jų gaminiai", new() { NameLT = "Silkės ir jų gaminiai" } },
   //         { "Lašišos ir jų gaminiai", new() { NameLT = "Lašišos ir jų gaminiai" } },
   //         { "Tunai ir jų gaminiai", new() { NameLT = "Tunai ir jų gaminiai" } },
   //         { "Ikrai", new() { NameLT = "Ikrai" } },
   //         { "Produktai iš surimio", new() { NameLT = "Produktai iš surimio" } },
   //         { "Jūrų kopūstai", new() { NameLT = "Jūrų kopūstai" } },
   //         { "Žuvies užtepelės ir paštetai", new() { NameLT = "Žuvies užtepelės ir paštetai" } },
   //         { "Rūkytos žuvys ir jūrų gėrybės", new() { NameLT = "Rūkytos žuvys ir jūrų gėrybės" } },
   //         { "Vytintos žuvys ir jūrų gėrybės", new() { NameLT = "Vytintos žuvys ir jūrų gėrybės" } },
   //         { "Kitos konservuotos žuvys ir jūrų gėrybės", new() { NameLT = "Kitos konservuotos žuvys ir jūrų gėrybės" } },
   //         { "Apdorotos jūrų gėrybės", new() { NameLT = "Apdorotos jūrų gėrybės" } },
   //         //Kulinarija
   //         { "Pagrindiniai patiekalai ir sriubos", new() { NameLT = "Pagrindiniai patiekalai ir sriubos" } },
   //         { "Miltiniai patiekalai", new() { NameLT = "Miltiniai patiekalai" } },
   //         { "Salotos ir mišrainės", new() { NameLT = "Salotos ir mišrainės" } },
   //         { "Užkandžiai", new() { NameLT = "Užkandžiai" } },
   //         { "Sumuštiniai", new() { NameLT = "Sumuštiniai" } },
   //         { "Švieži makaronai, virtiniai ir tešla", new() { NameLT = "Švieži makaronai, virtiniai ir tešla" } },
   //         //Šaldytos daržovės, grybai ir uogos
   //         { "Šaldytos daržovės ir jų mišiniai", new() { NameLT = "Šaldytos daržovės ir jų mišiniai" } },
   //         { "Šaldytos bulvės", new() { NameLT = "Šaldytos bulvės" } },
   //         { "Šaldytos uogos ir vaisiai", new() { NameLT = "Šaldytos uogos ir vaisiai" } },
   //         { "Šaldyti grybai", new() { NameLT = "Šaldyti grybai" } },
   //         //Ledai ir ledo kubeliai
   //         { "Ledai porcijomis", new() { NameLT = "Ledai porcijomis" } },
   //         { "Ledai dežutėse ir indeliuose", new() { NameLT = "Ledai dežutėse ir indeliuose" } },
   //         { "Ledo kubeliai", new() { NameLT = "Ledo kubeliai" } },
   //         //Šaldyti kulinarijos ir konditerijos gaminiai
   //         { "Šaldytos picos ir užkandžiai", new() { NameLT = "Šaldytos picos ir užkandžiai" } },
   //         { "Šaldyti koldūnai ir virtiniai", new() { NameLT = "Šaldyti koldūnai ir virtiniai" } },
   //         { "Šaldyta tešla", new() { NameLT = "Šaldyta tešla" } },
   //         { "Šaldytos bandelės ir pyragaičiai", new() { NameLT = "Šaldytos bandelės ir pyragaičiai" } },
   //         { "Šaldytas paruoštas vartojimui maistas", new() { NameLT = "Šaldytas paruoštas vartojimui maistas" } },
   //         { "Šaldyti vegetariški ir veganiški patiekalai", new() { NameLT = "Šaldyti vegetariški ir veganiški patiekalai" } },
   //         //Šaldyta mėsa
   //         { "Šaldyta mėsa", new() { NameLT = "Šaldyta mėsa" } },
   //         { "Šaldyta paukštiena", new() { NameLT = "Šaldyta paukštiena" } },
   //         //Šaldytos žuvys ir jūrų gėrybės
   //         { "Šaldyta žuvis", new() { NameLT = "Šaldyta žuvis" } },
   //         { "Šaldytos krevetės", new() { NameLT = "Šaldytos krevetės" } },
   //         { "Šaldytos jūrų gėrybės", new() { NameLT = "Šaldytos jūrų gėrybės" } },
   //         { "Žuvų piršteliai", new() { NameLT = "Žuvų piršteliai" } },
   //         { "Žuvies patiekalai", new() { NameLT = "Žuvies patiekalai" } },
   //         { "Šaldytos krabų lazdelės ir jų gaminiai", new() { NameLT = "Šaldytos krabų lazdelės ir jų gaminiai" } },
   //         //GĖRIMAI
   //         //Vanduo
   //         { "Gazuotas vanduo", new() { NameLT = "Gazuotas vanduo" } },
   //         { "Negazuotas vanduo", new() { NameLT = "Negazuotas vanduo" } },
   //         //Sultys, nektarai ir sulčių gėrimai
   //         { "Sultys", new() { NameLT = "Sultys" } },
   //         { "Nektarai", new() { NameLT = "Nektarai" } },
   //         { "Sulčių gėrimai", new() { NameLT = "Sulčių gėrimai" } },
   //         { "Vaisių kokteiliai ir glotnučiai", new() { NameLT = "Vaisių kokteiliai ir glotnučiai" } },
   //         //Gaivieji gėrimai
   //         { "Sirupai", new() { NameLT = "Sirupai" } },
   //         { "Gazuoti vaisvandeniai", new() { NameLT = "Gazuoti vaisvandeniai" } },
   //         { "Negazuoti vaisvandeniai", new() { NameLT = "Negazuoti vaisvandeniai" } },
   //         { "Energetiniai gėrimai", new() { NameLT = "Energetiniai gėrimai" } },
   //         { "Šalta ir fermentuota arbata", new() { NameLT = "Šalta ir fermentuota arbata" } },
   //         { "Šalta kava", new() { NameLT = "Šalta kava" } },
   //         { "Gira", new() { NameLT = "Gira" } },
   //         { "Sporto ir funkciniai gėrimai", new() { NameLT = "Sporto ir funkciniai gėrimai" } },
   //         { "Beržų sula", new() { NameLT = "Beržų sula" } },
   //         //Nealkoholiniai gėrimai
   //         { "Nealkoholinis alus", new() { NameLT = "Nealkoholinis alus" } },
   //         { "Nealkoholinis vynas", new() { NameLT = "Nealkoholinis vynas" } },
   //         { "Nealkoholinis putojantis vynas", new() { NameLT = "Nealkoholinis putojantis vynas" } },
   //         { "Nealkoholinis sidras", new() { NameLT = "Nealkoholinis sidras" } },
   //         { "Nealkoholinis žiemos vynas", new() { NameLT = "Nealkoholinis žiemos vynas" } },
   //         //Alus
   //         { "Mažųjų daryklų alus", new() { NameLT = "Mažųjų daryklų alus" } },
   //         { "Šviesusis alus", new() { NameLT = "Šviesusis alus" } },
   //         { "Kvietinis alus", new() { NameLT = "Kvietinis alus" } },
   //         { "Tamsusis alus", new() { NameLT = "Tamsusis alus" } },
   //         { "Alaus kokteiliai", new() { NameLT = "Alaus kokteiliai" } },
   //         { "Alaus pakuotės", new() { NameLT = "Alaus pakuotės" } },
   //         //Vynas
   //         { "Raudonasis vynas", new() { NameLT = "Raudonasis vynas" } },
   //         { "Rausvasis vynas", new() { NameLT = "Rausvasis vynas" } },
   //         { "Baltasis vynas", new() { NameLT = "Baltasis vynas" } },
   //         { "Šampanas", new() { NameLT = "Šampanas" } },
   //         { "Putojantis vynas", new() { NameLT = "Putojantis vynas" } },
   //         { "Vermutas", new() { NameLT = "Vermutas" } },
   //         { "Vyno gėrimai", new() { NameLT = "Vyno gėrimai" } },
   //         { "Žiemos vynas", new() { NameLT = "Žiemos vynas" } },
   //         //Sidrai ir kokteiliai
   //         { "Sidras", new() { NameLT = "Sidras" } },
   //         { "Kokteiliai", new() { NameLT = "Kokteiliai" } },
   //         //Stiprieji alkoholiniai gėrimai
   //         { "Viskis", new() { NameLT = "Viskis" } },
   //         { "Brendis", new() { NameLT = "Brendis" } },
   //         { "Degtinė", new() { NameLT = "Degtinė" } },
   //         { "Romas", new() { NameLT = "Romas" } },
   //         { "Džinas", new() { NameLT = "Džinas" } },
   //         { "Konjakas", new() { NameLT = "Konjakas" } },
   //         { "Tekila", new() { NameLT = "Tekila" } },
   //         { "Trauktinė", new() { NameLT = "Trauktinė" } },
   //         { "Likeris", new() { NameLT = "Likeris" } },
   //         //Kūdikių ir vaikų prekės
   //         //Pieno mišiniai
   //         { "Pradinio maitinimo pieno mišiniai", new() { NameLT = "Pradinio maitinimo pieno mišiniai" } },
   //         { "Paruošti vartoti pieno mišiniai", new() { NameLT = "Paruošti vartoti pieno mišiniai" } },
   //         { "Pieno mišiniai nuo 0+ mėn.", new() { NameLT = "Pieno mišiniai nuo 0+ mėn." } },
   //         { "Pieno mišiniai nuo 6+ mėn.", new() { NameLT = "Pieno mišiniai nuo 6+ mėn." } },
   //         { "Pieno mišiniai nuo 1+ metų.", new() { NameLT = "Pieno mišiniai nuo 1+ metų." } },
   //         { "Specializuoti pieno mišiniai", new() { NameLT = "Specializuoti pieno mišiniai" } },
   //         //Kūdikių košės
   //         { "Košės su pienu nuo 4 mėn.", new() { NameLT = "Košės su pienu nuo 4 mėn." } },
   //         { "Košės su pienu nuo 6 mėn.", new() { NameLT = "Košės su pienu nuo 6 mėn." } },
   //         { "Košės su pienu nuo 8 mėn.", new() { NameLT = "Košės su pienu nuo 8 mėn." } },
   //         { "Košės su pienu nuo 12 mėn.", new() { NameLT = "Košės su pienu nuo 12 mėn." } },
   //         { "Košės be pieno nuo 4 mėn.", new() { NameLT = "Košės be pieno nuo 4 mėn." } },
   //         { "Košės be pieno nuo 6 mėn.", new() { NameLT = "Košės be pieno nuo 6 mėn." } },
   //         { "Košės be pieno nuo 8 mėn.", new() { NameLT = "Košės be pieno nuo 8 mėn." } },
   //         { "Košės be pieno nuo 12 mėn.", new() { NameLT = "Košės be pieno nuo 12 mėn." } },
   //         //Kūdikių gėrimai ir užkandžiai
   //         { "Sausainiai, trapučiai ir džiūvėsiai", new() { NameLT = "Sausainiai, trapučiai ir džiūvėsiai" } },
   //         { "Sultys, nektarai ir kiti gėrimai", new() { NameLT = "Sultys, nektarai ir kiti gėrimai" } },
   //         { "Arbata ir arbatos gėrimai", new() { NameLT = "Arbata ir arbatos gėrimai" } },
   //         //Vaisinės ir desertinės tyrelės
   //         { "Vaisinės ir desertinės tyrelės nuo 4 mėn.", new() { NameLT = "Vaisinės ir desertinės tyrelės nuo 4 mėn." } },
   //         { "Vaisinės ir desertinės tyrelės nuo 6 mėn.", new() { NameLT = "Vaisinės ir desertinės tyrelės nuo 6 mėn." } },
   //         { "Vaisinės ir desertinės tyrelės nuo 8 mėn.", new() { NameLT = "Vaisinės ir desertinės tyrelės nuo 8 mėn." } },
   //         { "Vaisinės ir desertinės tyrelės nuo 12 mėn.", new() { NameLT = "Vaisinės ir desertinės tyrelės nuo 12 mėn." } },
   //         //Mėsos ir daržovių tyrelės
   //         { "Mėsos ir daržovių tyrelės nuo 4 mėn.", new() { NameLT = "Mėsos ir daržovių tyrelės nuo 4 mėn." } },
   //         { "Mėsos ir daržovių tyrelės nuo 6 mėn.", new() { NameLT = "Mėsos ir daržovių tyrelės nuo 6 mėn." } },
   //         { "Mėsos ir daržovių tyrelės nuo 8 mėn.", new() { NameLT = "Mėsos ir daržovių tyrelės nuo 8 mėn." } },
   //         { "Mėsos ir daržovių tyrelės nuo 12 mėn.", new() { NameLT = "Mėsos ir daržovių tyrelės nuo 12 mėn." } },
   //         //Vaikų higienos prekės
   //         { "Kosmetinė vata ir krapštukai", new() { NameLT = "Kosmetinė vata ir krapštukai" } },
   //         { "Šampūnai ir prausimosi priemonės", new() { NameLT = "Šampūnai ir prausimosi priemonės" } },
   //         { "Kremai, losjonai ir aliejai", new() { NameLT = "Kremai, losjonai ir aliejai" } },
   //         { "Burnos higienos priemonės", new() { NameLT = "Burnos higienos priemonės" } },
   //         //Sauskelnės ir servetelės
   //         { "Sauskelnės, dydžiai 0 ir 1", new() { NameLT = "Sauskelnės, dydžiai 0 ir 1" } },
   //         { "Sauskelnės, dydis 2", new() { NameLT = "Sauskelnės, dydis 2" } },
   //         { "Sauskelnės, dydis 3", new() { NameLT = "Sauskelnės, dydis 3" } },
   //         { "Sauskelnės, dydis 4", new() { NameLT = "Sauskelnės, dydis 4" } },
   //         { "Sauskelnės, dydis 5", new() { NameLT = "Sauskelnės, dydis 5" } },
   //         { "Sauskelnės, dydis 6+", new() { NameLT = "Sauskelnės, dydis 6+" } },
   //         { "Paklotai", new() { NameLT = "Paklotai" } },
   //         { "Drėgnosios servetelės", new() { NameLT = "Drėgnosios servetelės" } },
   //         { "Sauskelnės-kelnaitės", new() { NameLT = "Sauskelnės-kelnaitės" } },
   //         //Kūdikių ir vaikų žaislai
   //         { "Kūdikių ir lavinamieji žaislai", new() { NameLT = "Kūdikių ir lavinamieji žaislai" } },
   //         { "Automobilių ir veiksmo žaidimai", new() { NameLT = "Automobilių ir veiksmo žaidimai" } },
   //         { "Lėlės ir jų priedai", new() { NameLT = "Lėlės ir jų priedai" } },
   //         { "Kūrybiniai ir interaktyvūs žaislai", new() { NameLT = "Kūrybiniai ir interaktyvūs žaislai" } },
   //         { "Stalo žaidimai", new() { NameLT = "Stalo žaidimai" } },
   //         { "Dėlionės", new() { NameLT = "Dėlionės" } },
   //         { "Kiti žaislai", new() { NameLT = "Kiti žaislai" } },
   //         //"LEGO" konstruktoriai
   //         { "LEGO DUPBLO", new() { NameLT = "LEGO DUPBLO" } },
   //         { "LEGO FRIENDS", new() { NameLT = "LEGO FRIENDS" } },
   //         { "LEGO CLASSIC", new() { NameLT = "LEGO CLASSIC" } },
   //         { "LEGO DISNEY", new() { NameLT = "LEGO DISNEY" } },
   //         { "LEGO CITY", new() { NameLT = "LEGO CITY" } },
   //         { "LEGO CREATOR", new() { NameLT = "LEGO CREATOR" } },
   //         { "LEGO TECHNIC", new() { NameLT = "LEGO TECHNIC" } },
   //         { "LEGO NINJAGO", new() { NameLT = "LEGO NINJAGO" } },
   //         { "LEGO MARVEL SUPER HEROES", new() { NameLT = "LEGO MARVEL SUPER HEROES" } },
   //         { "LEGO SPEED CHAMPIONS", new() { NameLT = "LEGO SPEED CHAMPIONS" } },
   //         { "LEGO MINECRAFT", new() { NameLT = "LEGO MINECRAFT" } },
   //         { "LEGO HARRY POTTER", new() { NameLT = "LEGO HARRY POTTER" } },
   //         { "LEGO ICONS", new() { NameLT = "LEGO ICONS" } },
   //         //Priežiūros prekės
   //         { "Prekės mamoms", new() { NameLT = "Prekės mamoms" } },
   //         { "Maitinimo ir kūdikių priežiūros prekės", new() { NameLT = "Maitinimo ir kūdikių priežiūros prekės" } },
   //         { "Seilinukai", new() { NameLT = "Seilinukai" } },
   //         { "Kiti kūdikių priežiūros reikmenys", new() { NameLT = "Kiti kūdikių priežiūros reikmenys" } },
   //         //Švaros ir gyvūnų prekės
   //         //Gyvūnų prekės
   //         { "Sausas šunų ėdalas", new() { NameLT = "Sausas šunų ėdalas" } },
   //         { "Konservuotas šunų ėdalas", new() { NameLT = "Konservuotas šunų ėdalas" } },
   //         { "Šunų skanėstai", new() { NameLT = "Šunų skanėstai" } },
   //         { "Sausas kačių ėdalas", new() { NameLT = "Sausas kačių ėdalas" } },
   //         { "Konservuotas kačių ėdalas", new() { NameLT = "Konservuotas kačių ėdalas" } },
   //         { "Kačių skanėstai", new() { NameLT = "Kačių skanėstai" } },
   //         { "Gyvūnų kraikas", new() { NameLT = "Gyvūnų kraikas" } },
   //         { "Paukščių kraikas", new() { NameLT = "Paukščių kraikas" } },
   //         { "Kitų gyvunų ėdalas", new() { NameLT = "Kitų gyvunų ėdalas" } },
   //         { "Gyvūnų higienos produktai", new() { NameLT = "\"Gyvūnų higienos produktai" } },
   //         { "Gyvūnų priežiūros reikmenys", new() { NameLT = "Gyvūnų priežiūros reikmenys" } },
   //         { "Gyvūnų aksesuarai", new() { NameLT = "Gyvūnų aksesuarai" } },
   //         //Indų plovikliai
   //         { "Plovimo priemonės indaplovėms", new() { NameLT = "Plovimo priemonės indaplovėms" } },
   //         { "Indaplovių priežiūros priemonės", new() { NameLT = "Indaplovių priežiūros priemonės" } },
   //         { "Priemonės indams plauti", new() { NameLT = "Priemonės indams plauti" } },
   //         //Popieriniai gaminiai
   //         { "Tualetinis popierius", new() { NameLT = "Tualetinis popierius" } },
   //         { "Popieriniai rankšluosčiai", new() { NameLT = "Popieriniai rankšluosčiai" } },
   //         { "Popierinės nosinaitės", new() { NameLT = "Popierinės nosinaitės" } },
   //         //Priemonės valymui
   //         { "Šluostės, kempinėlės ir šepečiai", new() { NameLT = "Šluostės, kempinėlės ir šepečiai" } },
   //         { "Langų ir grindų valymo reikmenys", new() { NameLT = "Langų ir grindų valymo reikmenys" } },
   //         { "Buitinės ir darbo pirštinės", new() { NameLT = "Buitinės ir darbo pirštinės" } },
   //         { "Šiukšlių maišai", new() { NameLT = "Šiukšlių maišai" } },
   //         //Butinės chemijos prekės
   //         { "Virtuvės ir vonios kambario valikliai", new() { NameLT = "Virtuvės ir vonios kambario valikliai" } },
   //         { "Langų valikliai", new() { NameLT = "Langų valikliai" } },
   //         { "Nuovirų ir nuosėdų valikliai", new() { NameLT = "Nuovirų ir nuosėdų valikliai" } },
   //         { "Specialiosios paskirties valikliai", new() { NameLT = "Specialiosios paskirties valikliai" } },
   //         { "Šveitikliai", new() { NameLT = "Šveitikliai" } },
   //         { "Universalūs valikliai", new() { NameLT = "Universalūs valikliai" } },
   //         { "Grindų ir kilimų valikliai", new() { NameLT = "Grindų ir kilimų valikliai" } },
   //         { "Skalbyklių priežiūra", new() { NameLT = "Skalbyklių priežiūra" } },
   //         { "Nutekamųjų vamzdžių valikliai", new() { NameLT = "Nutekamųjų vamzdžių valikliai" } },
   //         { "Skystieji WC valikliai - gaivikliai", new() { NameLT = "Skystieji WC valikliai - gaivikliai" } },
   //         { "Kietieji WC valikliai - gaivikliai", new() { NameLT = "Kietieji WC valikliai - gaivikliai" } },
   //         { "Purškiamieji oro gaivikliai", new() { NameLT = "Purškiamieji oro gaivikliai" } },
   //         { "Oro gaivikliai", new() { NameLT = "Oro gaivikliai" } },
   //         { "Namų kvapai", new() { NameLT = "Namų kvapai" } },
   //         { "Parazitų naikinimo priemonės", new() { NameLT = "Parazitų naikinimo priemonės" } },
   //         //Skalbimo priemonės
   //         { "Skalbiamieji milteliai", new() { NameLT = "Skalbiamieji milteliai" } },
   //         { "Skalbinių minkštikliai", new() { NameLT = "Skalbinių minkštikliai"} },
   //         { "Skystos skalbimo priemonės", new() { NameLT = "Skystos skalbimo priemonės" } },
   //         { "Skalbiamieji lapeliai", new() { NameLT = "Skalbiamieji lapeliai" } },
   //         { "Dėmių valikliai ir balinimo priemonės", new() { NameLT = "Dėmių valikliai ir balinimo priemonės" } },
   //         { "Priemonės skalbti rankomis", new() { NameLT = "Priemonės skalbti rankomis" } },
   //         { "Audinių standikliai ir antistatikai", new() { NameLT = "Audinių standikliai ir antistatikai" } },
   //         //Maisto ruošimo ir laikymo indai
   //         { "Maisto gaminimo ir laikymo medžiagos", new() { NameLT = "Maisto gaminimo ir laikymo medžiago" } },
   //         { "Maisto produktų laikymo indai", new() { NameLT = "Maisto produktų laikymo indai" } },
   //         { "Kepimo formos", new() { NameLT = "Kepimo formos" } },
   //         { "Puodai ir keptuvės", new() { NameLT = "Puodai ir keptuvės" } },
   //         { "Maisto ruošimo įrankiai", new() { NameLT = "Maisto ruošimo įrankiai" } },
   //         { "Gertuvės ir termosai", new() { NameLT = "Gertuvės ir termosai" } },
   //         { "Kiti virtuvės reikmenys", new() { NameLT = "Kiti virtuvės reikmenys" } },
   //         //Kojinės ir apatinis trikotažas
   //         { "Moteriškos kojinės", new() { NameLT = "Moteriškos kojinės" } },
   //         { "Vyriškos kojinės", new() { NameLT = "Vyriškos kojinės" } },
   //         { "Pėdkelnės", new() { NameLT = "Pėdkelnės" } },
   //         { "Vaikiškos pėdkelnės", new() { NameLT = "Vaikiškos pėdkelnės" } },
   //         { "Apatinis trikotažas", new() { NameLT = "Apatinis trikotažas" } },
   //         { "Vaikiškos kojinės", new() { NameLT = "Vaikiškos kojinės" } },
   //         { "Mamų unija", new() { NameLT = "Mamų unija" } },
   //         //Namų apyvokos reikmenys
   //         { "Drabužių priežiūra", new() { NameLT = "Drabužių priežiūra" } },
   //         { "Avalynės priežiūros priemonės", new() { NameLT = "Avalynės priežiūros priemonės" } },
   //         { "Siuvimo ir mezgimo priemonės", new() { NameLT = "Siuvimo ir mezgimo priemonės" } },
   //         { "Rankšluosčiai", new() { NameLT = "Rankšluosčiai" } },
   //         { "Pledai", new() { NameLT = "Pledai" } },
   //         { "Vonios reikmenys", new() { NameLT = "Vonios reikmenys" } },
   //         { "Patalynė ir patalynės reikmenys", new() { NameLT = "Patalynė ir patalynės reikmenys" } },
   //         { "Galvaniniai elementai", new() { NameLT = "Galvaniniai elementai" } },
   //         { "Klijai", new() { NameLT = "Klijai" } },
   //         { "Kapų žvakės", new() { NameLT = "Kapų žvakės" } },
   //         { "Darbo ir remonto priemonės", new() { NameLT = "Darbo ir remonto priemonės" } },
   //         //Augalai ir jų priežiūra
   //         { "Trąšos", new() { NameLT = "Trąšos" } },
   //         { "Žemės ir substratai", new() { NameLT = "Žemės ir substratai" } },
   //         { "Sodo įrankiai", new() { NameLT = "Sodo įrankiai" } },
   //         { "Gėlės", new() { NameLT = "Gėlės" } },

			// This category contains items, for which no appropiate category was found
			{ "UNMAPPED", new() { NameLT = "UNMAPPED" } },
		};

		public static Dictionary<string, Category> GetCategoryDict() =>
			CategoryDict.ToDictionary(
				c => (string)c.Key.Clone(), c => (Category)c.Value.Clone()
			);
	}
}

