using Models;

namespace CategoryMap
{
    public static class StaticCategoryTree
	{
        private static Dictionary<string, Category> CategoryDict = new()
		{
			// Pieno produktai ir kiaušiniai
			{ "Pasterizuotas pienas", new() { NameLT = "Pasterizuotas pienas" } },
			{ "Pieno gėrimai", new() { NameLT = "Pieno gėrimai" } },
			{ "Ilgo galiojimo pienas", new() { NameLT = "Ilgo galiojimo pienas" } },
			{ "Sutirštintas pienas", new() { NameLT = "Sutirštintas pienas" } },
			{ "Sojų pienas", new() { NameLT = "Sojų pienas" } },
			{ "Augalinis pienas", new() { NameLT = "Augalinis pienas" } },
			{"Sviestas", new() { NameLT =  "Sviestas"} },
			{"Tepieji riebalų mišiniai", new() { NameLT = "Tepeji riebalų mišiniai" } },
			{"Margarinas", new() {NameLT = "Margarinas"} },
			{"Augaliniai sūrio pakaitalai", new() { NameLT = "Augaliniai sūrio pakaitalai" } },
			{"Augaliniai majonezo pakaitalai", new(){ NameLT = "Augaliniai majonezo pakaitalai" } },
			{"Augaliniai gėrimai", new() { NameLT = "Augaliniai gėrimai"} },
			{"Augaliniai grietinėlės pakaitalai", new() { NameLT = "Augaliniai grietinėlės pakaitalai" } },
			{"Augaliniai jogurto ir desertų pakaitalai", new() {NameLT = "Augaliniai jogurto ir desertų pakaitalai" } },
			{"Augaliniai sviesto pakaitalai", new() { NameLT = "Augaliniai sviesto pakaitalai" } },
			{"Pienas ir gėrimai be laktozės", new() { NameLT = "Pienas ir gėrimai be laktozės" } },
			{"Grietinė be laktozės", new() { NameLT = "Grietinė be laktozės" } },
			{"Jogurtai ir desertai be laktozės", new() { NameLT = "Jogurtai ir desertai be laktozės" } },
			{"Sūriai be laktozės", new() { NameLT = "Sūriai be laktozės"} },
			{"Sviestas ir margarinas be laktozės", new() { NameLT = "Sviestas ir margarinas be laktozės" } },
			{"Varškė be laktozės", new() { NameLT = "Varškė be laktozės" } },
			{"Grietinė", new() { NameLT = "Grietinė" } },
			{"Grietinėlė", new() { NameLT = "Grietinėlė" } },
			{"Fermentiniai sūriai", new() { NameLT = "Fermentiniai sūriai" } },
			{"Kietieji sūriai", new() { NameLT = "Kietieji sūriai" } },
			{"Pelėsiniai sūriai", new() { NameLT = "Pelėsiniai sūriai" } },
			{"Lydyti sūriai", new() { NameLT = "Lydyti sūriai" } },
			{"Varškės sūriai", new() { NameLT = "Varškės sūriai" } },
			{"Ožkų ir avių pieno sūriai", new() { NameLT = "Ožkų ir avių pieno sūriai" } },
			{"Mocarelos ir buratos sūriai", new() { NameLT = "Mocarelos ir buratos sūriai" } },
			{"Maskarponės ir rikotos sūriai", new() { NameLT = "Maskarponės ir rikotos sūriai" } },
			{"Fetos ir brinzos sūriai", new() { NameLT = "Fetos ir brinzos sūriai" } },
			{"Tepamieji sūriai", new() { NameLT = "Tepamieji sūriai" } },
			{"Sūriai, skirti kepti", new() { NameLT = "Sūriai, skirti kepti" } },
			{"Sūrio užkandžiai ir sūrio lazdelės", new() {NameLT = "Sūrio užkandžiai ir sūrio lazdelės" } },
			{"Majonezas", new() { NameLT = "Majonezas"} },
			{"Kefyras ir kefyro gėrimai", new() { NameLT = "Kefyras ir kefyro gėrimai" } },
			{"Rūgpienis", new() { NameLT = "Rūgpienis"} },
			{"Raugintos pasukos", new() { NameLT = "Raugintos pasukos" } },
			{"Jogurtai be pagardų", new() { NameLT = "Jogurtai be pagardų" } },
			{"Jogurtai su pagardais", new() { NameLT = "Jogurtai su pagardais" } },
			{"Geriamieji jogurtai", new() { NameLT = "Gėriamieji jogurtai" } },
			{"Desertiniai batonėliai", new() { NameLT = "Desertiniai batonėliai" } },
			{"Desertai", new() { NameLT = "Desertai" } },
			{"Varškė", new() { NameLT = "Varškė" } },
			{"Grūdėta varškė", new() { NameLT = "Grūdėta varškė" } },
			{"Tepamoji varškė", new() { NameLT = "Tepamoji varškė" } },
			{"Desertinė varškė", new() { NameLT = "Desertinė varškė" } },
			{"Varškės sūreliai", new() { NameLT = "Varškės sūreliai" } },
			{"Vištų kiaušinai", new() { NameLT = "Vištų kiaušiniai" } },
			{"Putpelių kiaušiniai", new() { NameLT = "Putpelių kiaušiniai"} },
			
			// Daržovės ir vaisiai
			{"Pomidorai ir agurkai", new() { NameLT = "Pomidorai ir agurkai"} },
            {"Paprikos ir baklažanai", new() { NameLT = "Paprikos ir baklažanai"} },
            {"Bulvės, morkos ir kopūstai", new() { NameLT = "Bulvės, morkos ir kopūstai"} },
            {"Svogūnai, porai ir česnakai", new() { NameLT = "Svogūnai, porai ir česnakai"} },
            {"Būrokėliai ir kiti šakniavaisiai", new() { NameLT = "Būrokėliai ir kiti šakniavaisiai"} },
            {"Salotos ir jų mišiniai", new() { NameLT = "Salotos ir jų mišiniai"} },
            {"Prieskoninės daržovės ir žolelės", new() { NameLT = "Prieskoninės daržovės ir žolelės"} },
            {"Kukurūzai, žirniai, pupelės ir smidrai", new() { NameLT = "Kukurūzai, žirniai, pupelės ir smidrai"} },
            {"Moliūgai ir cukinijos", new() { NameLT = "Moliūgai ir cukinijos"} },
            {"Marinuotos, raugintos ir sūdytos daržovės", new() { NameLT = "Marinuotos, raugintos ir sūdytos daržovės"} },
            {"Bananai", new() { NameLT = "Bananai"} },
            {"Citrusiniai vaisiai", new() { NameLT = "Citrusiniai vaisiai"} },
            {"Obuoliai ir kriaušės", new() { NameLT = "Obuoliai ir kriaušės"} },
            {"Vynuogės ir uogos", new() { NameLT = "Vynuogės ir uogos"} },
            {"Egzotiniai vaisiai", new() { NameLT = "Egzotiniai vaisiai"} },
            {"Melionai", new() { NameLT = "Melionai"} },
            {"Kaulavaisiai", new() { NameLT = "Kaulavaisiai"} },
            {"Avokadai", new() { NameLT = "Avokadai"} },
            {"Apdoroti vaisiai ir uogos", new() { NameLT = "Apdoroti vaisiai ir uogos"} },
            {"Grybai", new() { NameLT = "Grybai"} },

			//Bakalėja
            {"Švieži makaronai", new() { NameLT = "Švieži makaronai"} },
            {"Ilgieji ir plokštieji makaronai", new() { NameLT = "Ilgieji ir plokštieji makaronai"} },
            {"Trumpieji makaronai", new() { NameLT = "Trumpieji makaronai"} },
            {"Smulkieji makaronai", new() { NameLT = "Smulkieji makaronai"} },
            {"Vamzdeliniai ir lazanijos makaronai", new() { NameLT = "Vamzdeliniai ir lazanijos makaronai"} },
            {"Kiaušininiai makaronai", new() { NameLT = "Kiaušininiai makaronai"} },
            {"Pilno grūdo makaronai", new() { NameLT = "Pilno grūdo makaronai"} },
            {"Grikiai", new() { NameLT = "Grikiai"} },
            {"Kvietinės ir miežinės kruopos", new() { NameLT = "Kvietinės ir miežinės kruopos"} },
            {"Perlinės kruopos", new() { NameLT = "Perlinės kruopos"} },
            {"Manų kruopos", new() { NameLT = "Manų kruopos"} },
            {"Kitos krupos", new() { NameLT = "Kitos krupos"} },
            {"Dribsniai", new() { NameLT = "Dribsniai"} },
            {"Sausi pusryčiai", new() { NameLT = "Sausi pusryčiai"} },
            {"Dribsniai košėms", new() { NameLT = "Dribsniai košėms"} },
            {"Javainių batonėliai", new() { NameLT = "Javainių batonėliai"} },
            {"Bulvių traškučiai", new() { NameLT = "Bulvių traškučiai"} },
            {"Padažai traškučiams", new() { NameLT = "Padažai traškučiams"} },
            {"Kukurūzų traškučiai", new() { NameLT = "Kukurūzų traškučiai"} },
            {"Kepinta duona ir duonos traškučiai", new() { NameLT = "Kepinta duona ir duonos traškučiai"} },
            {"Kiti užkandžiai", new() { NameLT = "Kiti užkandžiai"} },
            {"Krekeriai ir sūrūs sausainiai", new() { NameLT = "Krekeriai ir sūrūs sausainiai"} },
            {"Kukurūzų lazdelės ir spragėsiai", new() { NameLT = "Kukurūzų lazdelės ir spragėsiai"} },
            {"Juodoji arbata", new() { NameLT = "Juodoji arbata"} },
            {"Žolelių arbata", new() { NameLT = "Žolelių arbata"} },
            {"Kita arbata", new() { NameLT = "Kita arbata"} },
            {"Šventinė arbata", new() { NameLT = "Šventinė arbata"} },
            {"Diabetinis maistas", new() { NameLT = "Diabetinis maistas"} },
            {"Sojų produktai", new() { NameLT = "Sojų produktai"} },
            {"Funkcinis maistas", new() { NameLT = "Funkcinis maistas"} },
            {"Kvietiniai miltai", new() { NameLT = "Kvietiniai miltai"} },
            {"Pilno grūdo miltai", new() { NameLT = "Pilno grūdo miltai"} },
            {"Kiti miltai", new() { NameLT = "Kiti miltai"} },
            {"Miltiniai mišiniai", new() { NameLT = "Miltiniai mišiniai"} },
            {"Sėlenos ir sėmenys", new() { NameLT = "Sėlenos ir sėmenys"} },
            {"Grynieji prieskoniai", new() { NameLT = "Grynieji prieskoniai"} },
            {"Pipirai", new() { NameLT = "Pipirai"} },
            {"Prieskonių mišiniai", new() { NameLT = "Prieskonių mišiniai"} },
            {"Universalūs prieskoniai", new() { NameLT = "Universalūs prieskoniai"} },
            {"Prieskonių ruošiniai patiekalams", new() { NameLT = "Prieskonių ruošiniai patiekalams"} },
            {"Prieskoniai mėsai", new() { NameLT = "Prieskoniai mėsai"} },
            {"Prieskoniai žuviai", new() { NameLT = "Prieskoniai žuviai"} },
            {"Marinatai", new() { NameLT = "Marinatai"} },
            {"Žolelių mišiniai", new() { NameLT = "Žolelių mišiniai"} },
            {"Greitai paruošiamos sriubos", new() { NameLT = "Greitai paruošiamos sriubos"} },
            {"Greitai paruošiami makaronai", new() { NameLT = "Greitai paruošiami makaronai"} },
            {"Greitai paruošiamos bulvių košės", new() { NameLT = "Greitai paruošiamos bulvių košės"} },
            {"Sultiniai", new() { NameLT = "Sultiniai"} },
            {"Huracán kava", new() { NameLT = "Huracán kava"} },
            {"Malta kava", new() { NameLT = "Malta kava"} },
            {"Kavos pupelės", new() { NameLT = "Kavos pupelės"} },
            {"Kavos kapsulės", new() { NameLT = "Kavos kapsulės"} },
            {"Tirpioji kava", new() { NameLT = "Tirpioji kava"} },
            {"Kavos kapsulės NESPRESSO® aparatams", new() { NameLT = "Kavos kapsulės NESPRESSO® aparatams"} },
            {"Kavos kapsulės Dolce Gusto® aparatams", new() { NameLT = "Kavos kapsulės Dolce Gusto® aparatams"} },
            {"Kakava", new() { NameLT = "Kakava"} },
            {"Kiti gėrimai", new() { NameLT = "Kiti gėrimai"} },
            {"Šventinė kava ir rinkiniai", new() { NameLT = "Šventinė kava ir rinkiniai"} },
            {"Konservuoti agurkai", new() { NameLT = "Konservuoti agurkai"} },
            {"Žaliosios alyvuogės", new() { NameLT = "Žaliosios alyvuogės"} },
            {"Juodosios alyvuogės", new() { NameLT = "Juodosios alyvuogės"} },
            {"Konservuoti pomidorai", new() { NameLT = "Konservuoti pomidorai"} },
            {"Konservuoti burokėliai", new() { NameLT = "Konservuoti burokėliai"} },
            {"Konservuoti kukurūzai", new() { NameLT = "Konservuoti kukurūzai"} },
            {"Konservuoti žirneliai", new() { NameLT = "Konservuoti žirneliai"} },
            {"Konservuotos pupelės", new() { NameLT = "Konservuotos pupelės"} },
            {"Konservuotos paprikos", new() { NameLT = "Konservuotos paprikos"} },
            {"Konservuoti daržovių mišiniai", new() { NameLT = "Konservuoti daržovių mišiniai"} },
            {"Kitos konservuotos ankštinės daržovės", new() { NameLT = "Kitos konservuotos ankštinės daržovės"} },
            {"Kitos konservuotos daržovės", new() { NameLT = "Kitos konservuotos daržovės"} },
            {"Konservuoti grybai", new() { NameLT = "Konservuoti grybai"} },
            {"Konservuoti vaisiai ir uogos", new() { NameLT = "Konservuoti vaisiai ir uogos"} },
            {"Uogienės ir džemai", new() { NameLT = "Uogienės ir džemai"} },
            {"Vaisių ir uogų tyrelės", new() { NameLT = "Vaisių ir uogų tyrelės"} },
            {"Medus", new() { NameLT = "Medus"} },
            {"Konservuotos sriubos", new() { NameLT = "Konservuotos sriubos"} },
            {"Ilgagrūdžiai ryžiai", new() { NameLT = "Ilgagrūdžiai ryžiai"} },
            {"Trumpagrūdžiai ir apvaliagrūdžiai ryžiai", new() { NameLT = "Trumpagrūdžiai ir apvaliagrūdžiai ryžiai"} },
            {"Rudieji ir laukiniai ryžiai", new() { NameLT = "Rudieji ir laukiniai ryžiai"} },
            {"Basmati ir kvapieji ryžiai", new() { NameLT = "Basmati ir kvapieji ryžiai"} },
            {"Plikyti ryžiai", new() { NameLT = "Plikyti ryžiai"} },
            {"Juodasis šokoladas", new() { NameLT = "Juodasis šokoladas"} },
            {"Baltasis šokoladas", new() { NameLT = "Baltasis šokoladas"} },
            {"Pieninis šokoladas", new() { NameLT = "Pieninis šokoladas"} },
            {"Šokoladiniai batonėliai", new() { NameLT = "Šokoladiniai batonėliai"} },
            {"Saldainiai ir šokoladas", new() { NameLT = "Saldainiai ir šokoladas"} },
            {"Sausainiai ir meduoliai", new() { NameLT = "Sausainiai ir meduoliai"} },
            {"Saldainių rinkiniai", new() { NameLT = "Saldainių rinkiniai"} },
            {"Kūčiukai", new() { NameLT = "Kūčiukai"} },
            {"Cukrus, saldikliai ir druska", new() { NameLT = "Cukrus, saldikliai ir druska"} },
            {"Kepinių papuošimai", new() { NameLT = "Kepinių papuošimai"} },
            {"Kepinių priedai", new() { NameLT = "Kepinių priedai"} },
            {"Sirupai", new() { NameLT = "Sirupai"} },
            {"Želė ir kiselius", new() { NameLT = "Želė ir kiselius"} },
            {"Kečupai", new() { NameLT = "Kečupai"} },
            {"Pomidorų padažai ir pasta", new() { NameLT = "Pomidorų padažai ir pasta"} },
            {"Majoneziniai padažai", new() { NameLT = "Majoneziniai padažai"} },
            {"Garstyčios", new() { NameLT = "Garstyčios"} },
            {"Krienai", new() { NameLT = "Krienai"} },
            {"Aitriųjų paprikų padažai", new() { NameLT = "Aitriųjų paprikų padažai"} },
            {"Kepsnių padažai", new() { NameLT = "Kepsnių padažai"} },
            {"Padažai salotoms", new() { NameLT = "Padažai salotoms"} },
            {"Padažai makaronams", new() { NameLT = "Padažai makaronams"} },
            {"Sojų padažai", new() { NameLT = "Sojų padažai"} },
            {"Desertiniai padažai", new() { NameLT = "Desertiniai padažai"} },
            {"Kiti padažai", new() { NameLT = "Kiti padažai"} },
            {"Užtepėlės", new() { NameLT = "Užtepėlės"} },
            {"Saulėgrąžų aliejus", new() { NameLT = "Saulėgrąžų aliejus"} },
            {"Alyvuogių aliejus", new() { NameLT = "Alyvuogių aliejus"} },
            {"Rapsų aliejus", new() { NameLT = "Rapsų aliejus"} },
            {"Kokosų aliejus", new() { NameLT = "Kokosų aliejus"} },
            {"Kitas aliejus", new() { NameLT = "Kitas aliejus"} },
            {"Actas ir koncentruotos citrinų sultys", new() { NameLT = "Actas ir koncentruotos citrinų sultys"} },
            {"Saldainiai", new() { NameLT = "Saldainiai"} },
            {"Sveriami saldainiai", new() { NameLT = "Sveriami saldainiai"} },
            {"Saldainių rinkiniai", new() { NameLT = "Saldainių rinkiniai"} },
            {"Batonėliai", new() { NameLT = "Batonėliai"} },
            {"Dražė", new() { NameLT = "Dražė"} },
            {"Guminukai", new() { NameLT = "Guminukai"} },
            {"Kramtomieji saldainiai", new() { NameLT = "Kramtomieji saldainiai"} },
            {"Pastilės, ledinukai ir kramtomoji guma", new() { NameLT = "Pastilės, ledinukai ir kramtomoji guma"} },
            {"Sausainiai", new() { NameLT = "Sausainiai"} },
            {"Vafliai", new() { NameLT = "Vafliai"} },
            {"Zefyrai", new() { NameLT = "Zefyrai"} },
            {"Šokolado ir riešutų kremai", new() { NameLT = "Šokolado ir riešutų kremai"} },
            {"Kiti saldumynai", new() { NameLT = "Kiti saldumynai"} },
            {"Žemės riešutai", new() { NameLT = "Žemės riešutai"} },
            {"Migdolų riešutai", new() { NameLT = "Migdolų riešutai"} },
            {"Lazdynų ir graikiniai riešutai", new() { NameLT = "Lazdynų ir graikiniai riešutai"} },
            {"Anakardžiai ir pistacijos", new() { NameLT = "Anakardžiai ir pistacijos"} },
            {"Kiti riešutai", new() { NameLT = "Kiti riešutai"} },
            {"Riešutų mišiniai", new() { NameLT = "Riešutų mišiniai"} },
            {"Riešutų ir džiovintų vaisių, uogų mišiniai", new() { NameLT = "Riešutų ir džiovintų vaisių, uogų mišiniai"} },
            {"Džiovinti vaisiai ir uogos", new() { NameLT = "Džiovinti vaisiai ir uogos"} },
            {"Sėklos", new() { NameLT = "Sėklos"} },
            {"Džiovintos daržovės ir grybai", new() { NameLT = "Džiovintos daržovės ir grybai"} },
            {"Šaltyje džiovinti vaisiai, uogos, daržovės", new() { NameLT = "Šaltyje džiovinti vaisiai, uogos, daržovės"} },
            {"Razinos ir spanguolės", new() { NameLT = "Razinos ir spanguolės"} },
            {"Abrikosai ir slyvos", new() { NameLT = "Abrikosai ir slyvos"} },
            {"Meksikos virtuvė", new() { NameLT = "Meksikos virtuvė"} },
            {"Tailando virtuvė", new() { NameLT = "Tailando virtuvė"} },
            {"Japonijos virtuvė", new() { NameLT = "Japonijos virtuvė"} },
            {"Kinijos virtuvė", new() { NameLT = "Kinijos virtuvė"} },

            //Kosmetika ir higiena
            {"Dantų šepetėliai", new() { NameLT = "Dantų šepetėliai"} },
            {"Dantų pastos", new() { NameLT = "Dantų pastos"} },
            {"Burnos skalavimo skysčiai", new() { NameLT = "Burnos skalavimo skysčiai"} },
            {"Dantų siūlai ir krapštukai", new() { NameLT = "Dantų siūlai ir krapštukai"} },
            {"Dantų protezų priežiūra", new() { NameLT = "Dantų protezų priežiūra"} },
            {"Makiažo valikliai ir veido prausikliai", new() { NameLT = "Makiažo valikliai ir veido prausikliai"} },
            {"Veido kremai", new() { NameLT = "Veido kremai"} },
            {"Naktiniai veido kremai", new() { NameLT = "Naktiniai veido kremai"} },
            {"Veido serumai ir paakių kremai", new() { NameLT = "Veido serumai ir paakių kremai"} },
            {"Veido kaukės", new() { NameLT = "Veido kaukės"} },
            {"Lūpų priežiūros priemonės", new() { NameLT = "Lūpų priežiūros priemonės"} },
            {"Kosmetinė vata ir krapštukai", new() { NameLT = "Kosmetinė vata ir krapštukai"} },
            {"Purškiamieji dezodorantai moterims", new() { NameLT = "Purškiamieji dezodorantai moterims"} },
            {"Purškiamieji dezodorantai vyrams", new() { NameLT = "Purškiamieji dezodorantai vyrams"} },
            {"Rutuliniai ir pieštukiniai dezodorantai moterims", new() { NameLT = "Rutuliniai ir pieštukiniai dezodorantai moterims"} },
            {"Rutuliniai ir pieštukiniai dezodorantai vyrams", new() { NameLT = "Rutuliniai ir pieštukiniai dezodorantai vyrams"} },
            {"Kvepalai moterims", new() { NameLT = "Kvepalai moterims"} },
            {"Kvepalai vyrams", new() { NameLT = "Kvepalai vyrams"} },
            {"Gabalinis tualetinis muilas", new() { NameLT = "Gabalinis tualetinis muilas"} },
            {"Skystas tualetinis muilas", new() { NameLT = "Skystas tualetinis muilas"} },
            {"Dušo želė", new() { NameLT = "Dušo želė"} },
            {"Vonios putos ir druska", new() { NameLT = "Vonios putos ir druska"} },
            {"Kūno odos priežiūros priemonės", new() { NameLT = "Kūno odos priežiūros priemonės"} },
            {"Saulės kosmetika", new() { NameLT = "Saulės kosmetika"} },
            {"Eteriniai aliejai", new() { NameLT = "Eteriniai aliejai"} },
            {"Kitos kūno priežiūros priemonės", new() { NameLT = "Kitos kūno priežiūros priemonės"} },
            {"Blakstienų tušai", new() { NameLT = "Blakstienų tušai"} },
            {"Makiažo pagrindai, pudros ir maskuokliai", new() { NameLT = "Makiažo pagrindai, pudros ir maskuokliai"} },
            {"Akių ir antakių pieštukai", new() { NameLT = "Akių ir antakių pieštukai"} },
            {"Lūpų dažai ir pieštukai", new() { NameLT = "Lūpų dažai ir pieštukai"} },
            {"Drėgnosios servetėlės", new() { NameLT = "Drėgnosios servetėlės"} },
            {"Pleistrai", new() { NameLT = "Pleistrai"} },
            {"Dezinfekcijos priemonės", new() { NameLT = "Dezinfekcijos priemonės"} },
            {"Prezervatyvai", new() { NameLT = "Prezervatyvai"} },
            {"Kitos medicininės prekės", new() { NameLT = "Kitos medicininės prekės"} },
            {"Vitaminų ir mineralų papildai", new() { NameLT = "Vitaminų ir mineralų papildai"} },
            {"Maisto papildai", new() { NameLT = "Maisto papildai"} },
            {"Namų vaistinėlė", new() { NameLT = "Namų vaistinėlė"} },
            {"Rankų odos priežiūros priemonės", new() { NameLT = "Rankų odos priežiūros priemonės"} },
            {"Pėdų odos priežiūros priemonės", new() { NameLT = "Pėdų odos priežiūros priemonės"} },
            {"Manikiūro ir pedikiūro reikmenys", new() { NameLT = "Manikiūro ir pedikiūro reikmenys"} },
            {"Skutimosi putos ir želė", new() { NameLT = "Skutimosi putos ir želė"} },
            {"Losjonai ir kremai po skutimosi", new() { NameLT = "Losjonai ir kremai po skutimosi"} },
            {"Skustuvai", new() { NameLT = "Skustuvai"} },
            {"Skutimosi peiliukai ir priedai", new() { NameLT = "Skutimosi peiliukai ir priedai"} },
            {"Depiliacinės priemonės", new() { NameLT = "Depiliacinės priemonės"} },
            {"Natūralus grožis", new() { NameLT = "Natūralus grožis"} },
            {"Plaukų šampūnai", new() { NameLT = "Plaukų šampūnai"} },
            {"Sausi plaukų šampūnai", new() { NameLT = "Sausi plaukų šampūnai"} },
            {"Plaukų balzamai", new() { NameLT = "Plaukų balzamai"} },
            {"Plaukų kaukės, serumai ir aliejus", new() { NameLT = "Plaukų kaukės, serumai ir aliejus"} },
            {"Šukuosenos formavimo priemonės", new() { NameLT = "Šukuosenos formavimo priemonės"} },
            {"Plaukų lakas", new() { NameLT = "Plaukų lakas"} },
            {"Plaukų dažai", new() { NameLT = "Plaukų dažai"} },
            {"Šukos ir šepečiai", new() { NameLT = "Šukos ir šepečiai"} },
            {"Higieniniai įklotai", new() { NameLT = "Higieniniai įklotai"} },
            {"Higieniniai paketai", new() { NameLT = "Higieniniai paketai"} },
            {"Tamponai", new() { NameLT = "Tamponai"} },
            {"Įklotai nelaikantiems šlapimo", new() { NameLT = "Įklotai nelaikantiems šlapimo"} },
            {"Intymios higienos servetelės", new() { NameLT = "Intymios higienos servetelės"} },
            {"Sauskelnės suaugusiems", new() { NameLT = "Sauskelnės suaugusiems"} },
            {"Kosmetikos rinkiniai", new() { NameLT = "Kosmetikos rinkiniai"} },
            {"", new() { NameLT = ""} },
            {"", new() { NameLT = ""} },
            {"", new() { NameLT = ""} },
            {"", new() { NameLT = ""} },
            {"", new() { NameLT = ""} },
            {"", new() { NameLT = ""} },
            {"", new() { NameLT = ""} },


			// Vaisiai

			// Mėsa

			// Kiaušiniai

			// ...

			//{ "Kiti", new() { NameLT = "Kiti" } },

			// This category contains items, for which no appropiate category was found
			{ "UNMAPPED", new() { NameLT = "UNMAPPED" } },
		};

		public static Dictionary<string, Category> GetCategoryDict() =>
			CategoryDict.ToDictionary(
				c => (string)c.Key.Clone(), c => (Category)c.Value.Clone()
			);
	}
}

